export default [
  {
    id: 'g1iuat6qeel4',
    name: 'First consistent',
    entries: {
      '33g3rpx3iu1u': ['Stonegrey', 'Dark Grey'],
      '7ceibvt70psc': ['Midnight Black', 'Black'],
      mdn3k0lx7bsf: ['Mystic Silver', 'Silver'],
      c3u2gfbgww0p: ['Caribean Sea', 'Turquoise'],
    },
  },
  {
    id: 'vsnjbl9e0w0m',
    name: 'This one has duplicate',
    entries: {
      pqmdrvdagkl4: ['Stonegrey', 'Dark Grey'],
      w1m7pjzjv2b: ['Stonegrey', 'Dark Grey'],
      '34p3747fl0v4': ['Midnight Black', 'Black'],
      qx4hgm9acs9b: ['Mystic Silver', 'Silver'],
    },
  },
  {
    id: 's86mzube4062',
    name: 'Second consistent',
    entries: {
      urtom2q3g7mh: ['Apple', 'Red'],
      yhe97ibfvzqm: ['Midnight Black', 'Black'],
      f63iv4vggs4n: ['Reaaally Dark', 'Black'],
      j2t01tqwoljm: ['Mystic Silver', 'Silver'],
    },
  },
  {
    id: 'so4pzrogpldf',
    name: 'This one has fork',
    entries: {
      v8bi9amlytyy: ['Apple', 'Red'],
      ky3p76l1nhjc: ['Apple', 'Green'],
      azc8wlhsbm5g: ['Midnight Black', 'Black'],
      crdmabqxtl83: ['Reaaally Dark', 'Black'],
      m7s3pa1asgch: ['Mystic Silver', 'Silver'],
    },
  },
  {
    id: 'z4ikuc2ltxst',
    name: 'Third consistent',
    entries: {
      '6oovfif9a8zk': ['Midnight Black', 'Black'],
      gs01b62u6xez: ['Caribean Sea', 'Turquoise'],
      '4kmua3d1vv7m': ['Reaaally Dark', 'Black'],
      '2l3njfk6h0ze': ['Mystic Silver', 'Silver'],
      y9z4z7dz07aa: ['Apple', 'Red'],
    },
  },
  {
    id: 'oc0q873zha5f',
    name: 'This one has simple cycle',
    entries: {
      vqpv5ctwffsl: ['Midnight Black', 'Black'],
      ee1qz7hgtru7: ['Stonegrey', 'Dark Grey'],
      cxfa9seu8tre: ['Dark Grey', 'Stonegrey'],
      bqixustlg014: ['Caribean Sea', 'Turquoise'],
      '8kliyjbnc86p': ['Reaaally Dark', 'Black'],
      '9jc1ppcqmtfs': ['Mystic Silver', 'Silver'],
      pnexb4a2quld: ['Apple', 'Red'],
    },
  },
  {
    id: 'whb7la5xwof6',
    name: 'This one has long cycle',
    entries: {
      s761mkdezpk9: ['Stonegrey', 'Space Grey'],
      us250xbfxmfa: ['Space Grey', 'Dark Grey'],
      mljelmepj2y9: ['Dark Grey', 'Grey'],
      zejt8038mlk9: ['Grey', 'Stonegrey'],
      bsm1x6opxja2: ['Midnight Black', 'Black'],
      lx47b2uvrhzw: ['Caribean Sea', 'Turquoise'],
      an1dors7rj7g: ['Reaaally Dark', 'Black'],
      cdq4wpsi78xq: ['Mystic Silver', 'Silver'],
      yp8dt5nsc5dr: ['Apple', 'Red'],
    },
  },
  {
    id: 'k04bfbr4cy09',
    name: 'This one has short chain',
    entries: {
      u72lu75furjp: ['Stonegrey', 'Space Grey'],
      '1c9to0gjc0zd': ['Space Grey', 'Dark Grey'],
      kyv9f2jjmsmv: ['Midnight Black', 'Black'],
      tqetl6fztohg: ['Caribean Sea', 'Turquoise'],
      gqo7rumfgib5: ['Reaaally Dark', 'Black'],
      mcn6kfsqks0m: ['Mystic Silver', 'Silver'],
    },
  },
  {
    id: 'rjzqj6d5gljf',
    name: 'This one has long chain',
    entries: {
      e6xk0fmyme52: ['Stonegrey', 'Space Grey'],
      xhyunpchxub9: ['Space Grey', 'Dark Grey'],
      so1qjgpjxojr: ['Dark Grey', 'Grey'],
      gs10ndc3w30e: ['Midnight Black', 'Black'],
      oajitj601r3u: ['Caribean Sea', 'Turquoise'],
      '7dx2ye8tjp8p': ['Reaaally Dark', 'Black'],
      '3x8tjla37q9u': ['Mystic Silver', 'Silver'],
      dprc8hkun47r: ['Apple', 'Red'],
    },
  },
  {
    id: 'ceqfyeuoqmq4',
    name: 'Fourth consistent',
    entries: {
      '9j3g3bfi2cyg': ['Stonegrey', 'Grey'],
      y72jbuahv5o9: ['Space Grey', 'Grey'],
      fb8i1g1l5j7s: ['Dark Grey', 'Grey'],
      nkjpe3b1ar4g: ['Apple', 'Red'],
      xqai6qza4jtt: ['Midnight Black', 'Black'],
      y86pa4y5ml7h: ['Caribean Sea', 'Turquoise'],
      '3w617ft9u2os': ['Mystic Silver', 'Silver'],
    },
  },
  {
    id: '9sjvanvisudp',
    name: 'This one has cycle & duplicate',
    entries: {
      s761mkdezpk9: ['Stonegrey', 'Space Grey'],
      us250xbfxmfa: ['Space Grey', 'Dark Grey'],
      mljelmepj2y9: ['Dark Grey', 'Grey'],
      zejt8038mlk9: ['Grey', 'Stonegrey'],
      bsm1x6opxja2: ['Midnight Black', 'Black'],
      lx47b2uvrhzw: ['Caribean Sea', 'Turquoise'],
      an1dors7rj7g: ['Reaaally Dark', 'Black'],
      ap0r3pasd93k: ['Caribean Sea', 'Turquoise'],
    },
  },
  {
    id: 'mucl0xmev4z3',
    name: 'Cycle & chain',
    entries: {
      s761mkdezpk9: ['a', 'b'],
      us250xbfxmfa: ['b', 'c'],
      mljelmepj2y9: ['c', 'd'],
      zejt8038mlk9: ['x', 'y'],
      bsm1x6opxja2: ['z', 'y'],
      lx47b2uvrhzw: ['q', 'w'],
      ap0r3pasd93k: ['w', 'e'],
      an1dors7rj7g: ['e', 'r'],
      bydnqbue1jla: ['r', 'q'],
    },
  },
];
